const categories = [
  {
    code: "OTHERS",
    name: "Others",
    id: 1,
    tokenId: -1,
    slug: "others",
  },
  {
    code: "Tesla",
    name: "Tesla",
    id: 3,
    tokenId: -1,
    slug: "tesla",
  },
  {
    code: "MDMA",
    name: "Diamond Avatar",
    id: 4,
    tokenId: -1,
    slug: "diamond_avatar",
  },
  {
    code: "PotionA",
    name: "Potion Avatar",
    id: 6,
    tokenId: -1,
    slug: "potion_avatar",
  },
  {
    code: "MML",
    name: "Musk USM LAND",
    id: 7,
    tokenId: -1,
    slug: "musk_usm_land",
  },
  {
    code: "MetamonUL",
    name: "Metamon USM LAND",
    id: 8,
    tokenId: -1,
    slug: "metamon_usm_land",
  },
  {
    code: "SNG",
    name: "SpaceXNaut Dog",
    id: 9,
    tokenId: -1,
    slug: "spacexanut_dog",
  },

  {
    code: "MPB",
    name: "Matrix Plus Box",
    id: 10,
    tokenId: -1,
    slug: "matrix_plus_box",
  },
  {
    code: "BMM",
    name: "Bake Musk Mixer",
    id: 11,
    tokenId: -1,
    slug: "bake_musk_mixer",
  },
  {
    code: "DING",
    name: "DING",
    id: 12,
    tokenId: -1,
    slug: "ding",
  },
  {
    code: "EggA",
    name: "Egg Avatar",
    id: 14,
    tokenId: -1,
    slug: "egg_avatar",
  },
  {
    code: "Potion",
    name: "Potion",
    id: 15,
    tokenId: -1,
    slug: "potion",
  },
  {
    code: "Diamond",
    name: "Black Diamond",
    id: 16,
    tokenId: 2,
    slug: "black_diamond",
  },
  {
    code: "Diamond",
    name: "Purple Diamond",
    id: 16,
    tokenId: 1,
    slug: "purple_diamond",
  },
  {
    code: "Diamond",
    name: "Yellow Diamond",
    id: 16,
    tokenId: 0,
    slug: "yellow_diamond",
  },
  {
    code: "Egg",
    name: "Egg",
    id: 17,
    tokenId: -1,
    slug: "egg",
  },
  {
    code: "BMBMUSK",
    name: "BMBMUSK",
    id: 18,
    tokenId: -1,
    slug: "bmbmusk",
  },
  {
    code: "BMBRACA",
    name: "BMBRACA",
    id: 19,
    tokenId: -1,
    slug: "bmbraca",
  },
  {
    code: "KISS",
    name: "Kiss-up State Land",
    id: 20,
    tokenId: -1,
    slug: "kiss_up_state_land",
  },
  {
    code: "MBOX",
    name: "Mystery Box",
    id: 21,
    tokenId: -1,
    slug: "mystery_box",
  },
  {
    code: "SRKD",
    name: "Super Rare Kiss-Up-Dog",
    id: 22,
    tokenId: -1,
    slug: "sr_kiss_up_dog",
  },
  {
    code: "DFD",
    name: "Dragon Fruit Dog",
    id: 26,
    tokenId: -1,
    slug: "dragon_fruit_dog",
  },
  {
    code: "SSRKD",
    name: "SSR Kiss-Up-Dog",
    id: 27,
    tokenId: -1,
    slug: "ssr_kiss_up_dog",
  },
  {
    code: "RACAPunk",
    name: "RACAPunk",
    id: 28,
    tokenId: -1,
    slug: "racapunk",
  },
];

export default categories;
